jobs:
  build:
    docker:
      - image: python:3.7.1
        environment:
          FLASK_APP: run.py
          FLASK_DEBUG: 1
    steps:
      - checkout
      - run:
          name: install deps
          command: pip install -r requirements/dev.txt

      - run:
          name: run tests
          command: pytest